ALTER TABLE watchlist_daily 
ADD COLUMN IF NOT EXISTS fundamental_score NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS revenue_growth_yoy NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS revenue_growth_qoq NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS gross_margin NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS eps_growth_qoq NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS eps_growth_yoy NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS rs_score_6m NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS inst_ownership_pct NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS market_cap_mln NUMERIC DEFAULT 0;
