"""
eTrader v5.0 — Opportunity Service
Service to manage and persist trade opportunities generated by technical patterns.
"""
from datetime import datetime, timezone
from app.core.logger import log_info, log_error
from app.core.supabase_client import get_supabase

async def create_stock_opportunity(
    ticker: str,
    entry_price: float,
    sl: float,
    tp1: float,
    tp2: float,
    reason: str,
    strength: str = "STRONG"
):
    """Persists a new stock opportunity into Supabase."""
    sb = get_supabase()
    try:
        # 1. Check if an active opportunity already exists for this ticker
        existing = sb.table("trade_opportunities")\
            .select("id")\
            .eq("ticker", ticker)\
            .eq("status", "active")\
            .execute()
            
        if existing.data:
            return # Skip if already active
            
        # 2. Insert new opportunity
        row = {
            "ticker": ticker,
            "trade_type": "long",
            "entry_zone_high": entry_price,
            "stop_loss": sl,
            "target_1": tp1,
            "target_2": tp2,
            "meta_score": 9.0 if strength == "STRONG" else 7.0,
            "status": "active",
            "reason": reason,
            "created_at": datetime.now(timezone.utc).isoformat()
        }
        
        sb.table("trade_opportunities").insert(row).execute()
        
        # 3. Log to system logs
        log_info("opportunity_service", f"🎯 New Opportunity created: {ticker} @ ${entry_price:.2f} (Reason: {reason})")
        
    except Exception as e:
        log_error("opportunity_service", f"Error creating opportunity for {ticker}: {e}")
